name: Build and Deploy LLM API to ECR and Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: envs-aws

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      API_USERNAME: ${{ secrets.API_USERNAME }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v4

    - name: Instalar Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    - name: Configurar credenciais AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login no Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Gerar arquivo .env
      run: |
        echo "API_USERNAME=${API_USERNAME}" >> .env
        echo "API_PASSWORD=${API_PASSWORD}" >> .env

    - name: Build imagem com Docker Compose
      run: |
        docker compose build

    - name: Tag e push para o ECR
      run: |
        docker tag llm-api:latest $ECR_REPOSITORY:latest
        docker push $ECR_REPOSITORY:latest

    - name: Acessar servidor e atualizar com Docker Compose
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.TARGET_HOST }}
        username: ${{ secrets.TARGET_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/rafael/app
          echo "API_USERNAME=${{ env.API_USERNAME }}" > .env
          echo "API_PASSWORD=${{ env.API_PASSWORD }}" >> .env
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY }}
          docker compose pull
          docker compose up -d
